version: '3.8'
services:
  mongodb-server:
    build: .
    image: mongodb-server
    container_name: mongodb-server
    volumes: 
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      
