version: "3.8"
services:
  mongodb-server:
    image: mongo:8.2.2
    container_name: mongodb-server
    volumes:
      - ./data:/data/db
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
