version: "3"
services:
  nginx:
    image: nginx:stable-alpine3.23-perl
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - 80:80
      - 443:443
