services:
  cache:
    image: redis:8.0-M03-alpine
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass password
    command: redis-server --requirepass password
    volumes: 
      - ./cache:/data