services:
  elasticsearch:
    image: elasticsearch:8.17.2
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - "ELASTIC_PASSWORD=password"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:8080"
  kibana:
    image: kibana:8.17.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"