services:
  jenkins:
    image: jenkins/jenkins:2.504.1-lts-jdk21
    container_name: jenkins
    ports:
      - "${JENKINS_HTTP_PORT}:8080"
      - "${JENKINS_SLAVE_PORT}:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "${JENKINS_JAVA_OPTS}"
    env_file:
      - .env