version: "3.7"
services:
  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:5.7.44
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=sinarelektronik
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%

