services:
  postgres:
    restart: unless-stopped
    image: postgres:17.2-alpine3.21
    hostname: postgres
    networks:
      - semaphore-network
    volumes:
      - ./semaphore-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: semaphore
      POSTGRES_DB: semaphore

  dind:
    image: docker:29.1.3-dind
    container_name: semaphore-dind
    restart: unless-stopped
    privileged: true
    networks:
      - semaphore-network
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      [
        "dockerd",
        "--host=tcp://0.0.0.0:2375",
        "--host=unix:///var/run/docker.sock",
      ]
    volumes:
      - dind-storage:/var/lib/docker

  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - semaphore-network
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN: wissensalt
      SEMAPHORE_ADMIN_PASSWORD: Password123!
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      SEMAPHORE_LDAP_ACTIVATED: "no"
      DOCKER_HOST: tcp://dind:2375
      TZ: UTC
    depends_on:
      - postgres
      - dind

networks:
  semaphore-network:
    driver: bridge

volumes:
  dind-storage:
